import type { Metadata } from 'next';
import Image from 'next/image';

export const metadata: Metadata = {
  title: '關於 | 我的 Next.js 部落格',
  description: '了解更多關於這個部落格和作者的信息',
};

export default function About() {
  return (
    <div className="about-page">
      {/* Hero section */}
      <section className="mb-12 text-center">
        <h1 className="text-3xl md:text-4xl font-bold mb-6">關於此部落格</h1>
        <div className="max-w-3xl mx-auto">
          <p className="text-xl text-gray-600 mb-8">
            一個結合 AI 協作與極簡開發的現代化 React 部落格
          </p>
        </div>
        <div className="relative h-60 md:h-80 w-full rounded-lg overflow-hidden mb-8">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-500/20 to-purple-500/20 z-10"></div>
          <div className="absolute inset-0 flex items-center justify-center z-20">
            <h2 className="text-4xl md:text-5xl font-bold text-white shadow-text">Ian's Vibe Coding Blog</h2>
          </div>
        </div>
      </section>

      {/* Blog bilingual summary section */}
      <section className="mb-12 p-8 bg-gradient-to-br from-sky-50 to-indigo-50 rounded-xl shadow-sm">
        <h2 className="text-2xl font-bold mb-4">部落格概述 | Blog Overview</h2>
        <div className="space-y-4">
          <p className="text-lg">
            這是一個由「純 React + TypeScript」打造的現代化部落格，強調極簡 vibe coding、AI 協作，以及內容與結構的彈性。本站內容大多由 Claude 產生 React 組件，並結合 Windsurf OpenAI 進行架構整理，讓寫作流程極度簡化。
          </p>
          <p className="text-gray-600 italic">
            <strong>English:</strong> A modern blog built with pure React + TypeScript, focusing on minimal vibe coding, AI collaboration, and flexible content structure. Most content is generated by Claude as React components and organized with Windsurf OpenAI, making the writing workflow extremely simple.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mt-8">
          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h3 className="text-xl font-semibold mb-4">特色 | Features</h3>
            <ul className="space-y-3">
              <li className="flex items-start">
                <span className="text-blue-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">純 React + TypeScript，未來也可能用 Vite 重構</p>
                  <p className="text-gray-600 text-sm">Pure React + TypeScript; may use Vite in the future</p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-blue-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">AI 協作（Claude + Windsurf OpenAI）</p>
                  <p className="text-gray-600 text-sm">AI Collaboration (Claude + Windsurf OpenAI)</p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-blue-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">極簡 vibe coding，幾乎不需要手動 coding</p>
                  <p className="text-gray-600 text-sm">Minimal vibe coding, almost no manual coding required</p>
                </div>
              </li>
            </ul>
          </div>

          <div className="bg-white p-6 rounded-lg shadow-sm">
            <h3 className="text-xl font-semibold mb-4">優勢 | Advantages</h3>
            <ul className="space-y-3">
              <li className="flex items-start">
                <span className="text-green-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">部署到 Vercel 只需數秒鐘，重構網站只需數分鐘</p>
                  <p className="text-gray-600 text-sm">Deploys to Vercel in seconds, refactor in minutes</p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">GitHub 版控、Vercel 雲端部署，全流程免費</p>
                  <p className="text-gray-600 text-sm">Free workflow: GitHub version control + Vercel cloud deployment</p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-500 mr-2">✦</span>
                <div>
                  <p className="font-medium">靈活的內容定制，無固定模板限制</p>
                  <p className="text-gray-600 text-sm">Flexible content customization without template limitations</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </section>
      
      {/* About blog section */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6 pb-2 border-b border-gray-200">部落格簡介</h2>
        <div className="space-y-4">
          <p>
            這個部落格的核心特色是純 React + TypeScript，並不是特定於 Next.js，未來我也可能會用 Vite 來做一個新的 blog。這裡的內容、結構與流程，都是「vibe coding」的產物，以最純粹的 React + TypeScript 來呈現。
          </p>
          <p>
            一開始我曾用 MDX，但發現 Claude 產生的 React 組件並不容易直接放進 MDX，會遇到很多問題。因此我找到最好的解決方案，就是直接用純 React + TypeScript 撰寫所有 blog 內容。
          </p>
          <p>
            本站的內容大多是由 Claude 產生 React 組件，再用 Claude 與 Windsurf OpenAI 協作整理、架構這個網站。我的目標是讓寫作流程盡量簡單，大部分內容都是「vibe code」產生，幾乎不需要手動 coding。
          </p>
        </div>
      </section>
      
      {/* About author section */}
      <section className="mb-12 bg-white p-8 rounded-xl shadow-sm">
        <div className="flex flex-col md:flex-row items-center gap-8">
          <div className="w-40 h-40 rounded-full overflow-hidden bg-gray-100 flex items-center justify-center">
            {/* 如果有作者照片，可以啟用下面的 Image 組件 */}
            {/* <Image src="/images/author.jpg" alt="Ian" width={160} height={160} /> */}
            <span className="text-5xl text-gray-300">👤</span>
          </div>
          
          <div className="flex-1">
            <h2 className="text-2xl font-bold mb-4">關於作者</h2>
            <p className="mb-4">
              跨領域職涯，歷練工程、管理、業務與創業，熟悉企業運作與產品推廣。現專注於低代碼/無代碼（Low-Code/No-Code）與 AI 應用，持續探索創新技術。
            </p>
            <div className="flex flex-wrap gap-3 mb-6">
              <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm">Low-Code/No-Code</span>
              <span className="bg-purple-100 text-purple-800 px-3 py-1 rounded-full text-sm">AI 應用</span>
              <span className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm">React</span>
              <span className="bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm">TypeScript</span>
            </div>
            <div className="flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <a href="mailto:ian@wo94.top" className="text-blue-600 hover:text-blue-800 transition-colors">
                ian@wo94.top
              </a>
            </div>
          </div>
        </div>
      </section>
      
      {/* Tech stack section */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6 pb-2 border-b border-gray-200">技術棧</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-white p-6 rounded-lg shadow-sm text-center hover:shadow-md transition-shadow">
            <div className="text-blue-500 text-3xl mb-2">⟲</div>
            <div className="font-semibold">Next.js</div>
            <div className="text-gray-500 text-sm">v15.3.2</div>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-sm text-center hover:shadow-md transition-shadow">
            <div className="text-blue-500 text-3xl mb-2">⚛</div>
            <div className="font-semibold">React</div>
            <div className="text-gray-500 text-sm">v19.0.0</div>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-sm text-center hover:shadow-md transition-shadow">
            <div className="text-blue-500 text-3xl mb-2">𝓣</div>
            <div className="font-semibold">TypeScript</div>
            <div className="text-gray-500 text-sm">v5.0+</div>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-sm text-center hover:shadow-md transition-shadow">
            <div className="text-blue-500 text-3xl mb-2">🌊</div>
            <div className="font-semibold">Tailwind CSS</div>
            <div className="text-gray-500 text-sm">v4.0+</div>
          </div>
        </div>
      </section>
      
      {/* Contact CTA section */}
      <section className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white p-8 rounded-xl text-center">
        <h2 className="text-2xl font-bold mb-4">想了解更多？</h2>
        <p className="mb-6 max-w-2xl mx-auto">
          如果您對 vibe coding、React 開發或 AI 協作感興趣，或有任何問題，歡迎隨時與我聯繫！
        </p>
        <a 
          href="mailto:ian@wo94.top" 
          className="inline-block bg-white text-blue-600 px-6 py-3 rounded-lg font-medium hover:bg-blue-50 transition-colors"
        >
          立即聯繫
        </a>
      </section>
      
      <style jsx>{`
        .shadow-text {
          text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
        }
      `}</style>
    </div>
  );
}
