import Link from 'next/link';
import PostCard from '../components/blog/PostCard';
import { getAllPosts } from '../data/posts';

export default function Home() {
  const allPosts = getAllPosts();
  const recentPosts = allPosts.slice(0, 3); // 只顯示最近的3篇文章
  
  return (
    <div className="home-page">
      {/* Blog bilingual summary section */}
      <section className="blog-summary mb-8 p-6 bg-gray-50 rounded shadow">
        <h2 className="text-2xl font-bold mb-2">Ian's Vibe Coding Blog</h2>
        <p className="mb-2">
          這是一個由「純 React + TypeScript」打造的現代化部落格，強調極簡 vibe coding、AI 協作，以及內容與結構的彈性。本站內容大多由 Claude 產生 React 組件，並結合 Windsurf OpenAI 進行架構整理，讓寫作流程極度簡化。
        </p>
        <p className="text-gray-600 text-sm mb-2">
          <strong>English:</strong> A modern blog built with pure React + TypeScript, focusing on minimal vibe coding, AI collaboration, and flexible content structure. Most content is generated by Claude as React components and organized with Windsurf OpenAI, making the writing workflow extremely simple.
        </p>
        <ul className="list-disc pl-5 mb-2">
          <li>純 React + TypeScript，未來也可能用 Vite 重構。<br/><span className="text-gray-600 text-xs">Pure React + TypeScript; may use Vite in the future.</span></li>
          <li>AI 協作（Claude + Windsurf OpenAI）。<br/><span className="text-gray-600 text-xs">AI Collaboration (Claude + Windsurf OpenAI).</span></li>
          <li>極簡 vibe coding，幾乎不需要手動 coding。<br/><span className="text-gray-600 text-xs">Minimal vibe coding, almost no manual coding required.</span></li>
          <li>部署到 Vercel 只需數秒鐘，重構網站只需數分鐘。<br/><span className="text-gray-600 text-xs">Deploys to Vercel in seconds, refactor in minutes.</span></li>
          <li>GitHub 版控、Vercel 雲端部署，全流程免費。<br/><span className="text-gray-600 text-xs">Free workflow: GitHub version control + Vercel cloud deployment.</span></li>
        </ul>
      </section>
      <section className="hero">
        <h1>歡迎來到我的技術部落格</h1>
        <p>分享 Next.js、React 和 TypeScript 的學習心得和最佳實踐</p>
        <div className="hero-actions">
          <Link href="/blog" className="primary-button">
            瀏覽所有文章
          </Link>
          <Link href="/about" className="secondary-button">
            了解更多
          </Link>
        </div>
      </section>
      
      <section className="featured-content">
        <h2 className="section-title">精選文章</h2>
        <div className="posts-grid">
          {recentPosts.map(post => (
            <PostCard key={post.slug} post={post} />
          ))}
        </div>
        <div className="view-all">
          <Link href="/blog">
            查看所有文章
          </Link>
        </div>
      </section>
      
      <section className="newsletter">
        <h2>訂閱我的最新文章</h2>
        <p>不定期發送最新文章和技術資訊，絕不濫發郵件</p>
        <form className="subscribe-form">
          <input type="email" placeholder="您的郵箱地址" required />
          <button type="submit">訂閱</button>
        </form>
      </section>
    </div>
  );
}
